# Generated by Django 6.0.1 on 2026-02-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_employer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='EmployerRequest',
        ),
    ]
