# Generated by Django 6.0.1 on 2026-02-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_studentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='picture',
        ),
    ]
