# Generated by Django 6.0.1 on 2026-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_studentaccount_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='bio',
            field=models.TextField(blank=True, default='Add Bio', null=True),
        ),
    ]
