# Generated by Django 6.0.1 on 2026-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_studentaccount_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('contact_person', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('webid', models.TextField(unique=True)),
                ('company_description', models.TextField(blank=True, default='Add company description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
