# Generated by Django 6.0.1 on 2026-02-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_employeraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillInterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='proposed_salary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobPostingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='jobs.jobposting')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.skillinteresttag')),
            ],
            options={
                'ordering': ['tag__tag_name'],
                'unique_together': {('job', 'tag')},
            },
        ),
    ]
