# Generated by Django 6.0.1 on 2026-02-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_skillinteresttag_jobposting_proposed_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkillInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_webid', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='jobs.skillinteresttag')),
            ],
            options={
                'ordering': ['tag__tag_name'],
                'unique_together': {('student_webid', 'tag')},
            },
        ),
    ]
