# Generated by Django 6.0.1 on 2026-02-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_studentskillinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
