# Generated by Django 6.0.1 on 2026-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeraccount',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
