# Generated by Django 6.0.1 on 2026-02-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_employeraccount_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_webid', models.TextField()),
                ('student_webid', models.TextField()),
                ('resource_url', models.TextField()),
                ('resume_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('employer_webid', 'student_webid', 'resource_url')},
            },
        ),
    ]
