# Generated by Django 6.0.1 on 2026-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_accessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_webid', models.TextField()),
                ('student_webid', models.TextField()),
                ('resource_url', models.TextField()),
                ('resume_id', models.IntegerField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('employer_webid', 'student_webid', 'resource_url')},
            },
        ),
        migrations.DeleteModel(
            name='AccessRequest',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
