# Generated by Django 6.0.1 on 2026-03-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_resourcepermission_delete_accessrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.resume'),
        ),
    ]
