# Generated by Django 6.0.1 on 2026-03-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobapplication_resume_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume_id',
            new_name='resume',
        ),
    ]
